import "./globals.css";

import Navbar from "@/components/Navigation/Navbar";
// import Consultation from "@/components/Navigation/Consultation_button";

import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ConditionalComponents from "@/components/other/ConditionalComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {/* <Consultation /> */}
        <Toaster position="top-center" />
        {children}
        <ConditionalComponents />
      </body>
    </html>
  );
}
