import "./globals.css";
import { Inter } from "next/font/google";
import AppWrapper from "../components/AppWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppWrapper fontClass={inter.className}>{children}</AppWrapper>
    </html>
  );
}
